### ISSUE TITLE
Any better way to check if the permission is given?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ColeMurray/UsageStatsSample#1]
I've tried to check the permission, but I've failed (posted about it here: http://stackoverflow.com/q/28921136/878126 ) .

It's just that checking that the list/map is empty assumes that the result being empty mean that the permission isn't granted...

**Comment by ColeMurray** [comment]
Hey android dev,

I'm not sure if it would be possible to check the permission the way you
have since it is a hidden permission. In my example, I used a similar check
to yours, which I have found common among others using the usage stats
manager.

Is there a reason to avoid the workaround?

**Comment by AndroidDeveloperLB** [comment]
Well, it's because it also assumes something - that the code will not change.

Also, now that I've checked it again, it seems it doesn't work. Probably had a typo which made it look like it's ok.

**Comment by ColeMurray** [comment]
Yes it does assume that. Android's current available methods are somewhat
broken for this. Hopefully, we will see updates in the near future that
allows us to better utilize this functionality.

Do you have a github with the code available to look over? I could possible
do a quick lookover and assist

-Cole

On Sat, Mar 7, 2015 at 3:51 PM, AndroidDeveloperLB <notifications@github.com

**Comment by AndroidDeveloperLB** [comment]
I've updated the code and now it works. Still not sure if it really works or not.
I've posted about the issue here:
https://code.google.com/p/android/issues/detail?id=158777
Please star/comment/both if you can&wish.
The code I've played with is based on yours, and is published there.

**Comment by ColeMurray** [comment]
Glad to hear you got it working.

I'm not sure if you can perform the permission check since it is a hidden
permission.

Hopefully we will hear something back.

Best,

Cole

On Sat, Mar 7, 2015 at 4:07 PM, AndroidDeveloperLB <notifications@github.com

**Comment by AndroidDeveloperLB** [comment]
is it possible to empty those stats? This way I could see that this method works even when there are no statistics.

**Comment by ColeMurray** [comment]
I'm a bit confused by what you mean when you say 'empty the stats'?

Do you mean showing them in the log? Yes this is possible, it is included
in my sample

**Comment by AndroidDeveloperLB** [comment]
No, I mean reset them, so that there won't be anything to get after that, till the user launches an app again.

**Comment by ColeMurray** [comment]
You cannot reset the usageStats as they are part of the system. You could change the calendar times you are querying to the current time if that's what you are asking.

**Comment by AndroidDeveloperLB** [comment]
Not even with root?
It must be somewhere in the file system...
About changing the time, that's the thing. When I set it from now to now , the check fails. Even if I do from one second ago to now, it fails.
